### ISSUE TITLE
Negative SNF entries

### ISSUE THREAD

**Issue by thchr** [wildart/SmithNormalForm.jl#1]
First off, thanks for making this package available; it's great!

I noticed that the SNF diagonal entries or invariant factors are occasionally returned negative. 
Here's a reasonably minimal example (albeit with a not-so-minimal matrix):
```julia
A = [1 1 0 0 0 1 1 0 0 0 1 0 1 0 # 10×14 Array{Int64,2}
     0 0 2 0 0 2 2 0 0 0 0 1 2 0
     0 0 0 1 1 0 0 1 1 2 1 1 1 2
     1 1 0 0 0 0 0 1 1 0 1 0 0 1
     0 0 2 0 0 0 0 2 2 0 0 1 0 2
     0 0 0 1 1 1 1 0 0 2 1 1 2 1
     1 0 1 0 1 0 1 2 1 1 1 1 1 2
     0 1 1 1 0 1 0 1 2 1 1 1 1 2
     1 0 1 0 1 2 1 0 1 1 1 1 2 1
     0 1 1 1 0 1 2 1 0 1 1 1 2 1]

smith(A).SNF
10-element Array{Int64,1}:
  1
  1
 -1 # <-- negative entry
  1
  1
  1
  0
  0
  0
  0
```

Of course, the invariant factors are strictly only defined up to a sign, but it seems several authors adopt a convention of positivity for them (e.g. https://www.math.tamu.edu/~rojas/kannanbachemhermitesmith79.pdf and http://www.numbertheory.org/php/smith.html). 
A definite sign by convention is rather useful, so this would be nice to ensure, I think.

Also, any plans to register this package?

**Comment by marouanehanhasse** [comment]
Hi, 
i have an issue which is , i can't add the package on julia 0.7 it shows me this error message:
ERROR: git object 0.2.0 could not be found

**Comment by wildart** [comment]
@marouanehanhasse try
```
pkg> add https://github.com/wildart/SmithNormalForm.jl.git#v0.2.0
```

**Comment by marouanehanhasse** [comment]
thanks it's working now

**Comment by thchr** [comment]
For the record, I ended up wrapping this package's `smith` function in a `_smith` function that ensures positivity of the SNF factors via:
```jl
function _smith(X::AbstractMatrix; inverse=true, debug=false)
    F = smith(X, inverse=inverse, debug=debug)
    # To guarantee SNFⱼ = Λⱼ ≥ 0 we absorb the sign of Λ into T and T⁻¹, s.t.
    #    Λ′ = Λ*sign(Λ),   T′ = sign(Λ)*T,    and    T⁻¹′ = T⁻¹*sign(Λ),
    # with the convention that sign(0) = 1. Then we still have that X = SΛT = SΛ′T′
    # and also that Λ = S⁻¹XT⁻¹ ⇒ Λ′ = S⁻¹XT⁻¹′.
    for j in eachindex(F.SNF)
        Λⱼ = F.SNF[j]
        if Λⱼ < 0
            @views F.T[j,:]    .*= -1 # T′   = sign(Λ)*T    [rows]
            @views F.Tinv[:,j] .*= -1 # T⁻¹′ = T⁻¹*sign(Λ)  [columns]
            F.SNF[j] = abs(Λⱼ)        # Λ′ = Λ*sign(Λ)
        end
    end

    return F
end
```

**Comment by wildart** [comment]
Nice trick. I'll add it to the new version.
